package engine_test

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/theclifmeister/kingpin/internal/content"
	"github.com/theclifmeister/kingpin/internal/engine"
	"github.com/theclifmeister/kingpin/internal/events"
	"github.com/theclifmeister/kingpin/internal/game"
	"github.com/theclifmeister/kingpin/internal/harness"
)

// TestEveryKindIsCuedOrNot (#301): every event kind either gives the cue
// cueKinds names for it or none, and CueOf agrees with the table, so a
// kind added to events.All is decided here.
func TestEveryKindIsCuedOrNot(t *testing.T) {
	t.Parallel()
	cued := 0
	for _, e := range events.All {
		want := engine.CueKindOf(e.Kind())
		c, ok := engine.CueOf(e)
		if ok != (want != "") {
			t.Errorf("%s: CueOf gives a cue %v, the table says %q", e.Kind(), ok, want)
			continue
		}
		if ok {
			cued++
			if c.Kind != want {
				t.Errorf("%s: CueOf gives %s, the table says %s", e.Kind(), c.Kind, want)
			}
		}
	}
	if cued < 40 {
		t.Fatalf("only %d kinds cued", cued)
	}
}

// TestCuesCarryIDs (#301): on a played run every cue names what it is
// about in ids a front end finds in the view: a corner flip its corner
// and both owners, a shipment its route and both ends, a crew cue its
// member.
func TestCuesCarryIDs(t *testing.T) {
	t.Parallel()
	cfg := content.MustLoad()
	s, err := engine.New(cfg)
	if err != nil {
		t.Fatal(err)
	}
	var cues []engine.Cue
	s.Subscribe(func(e events.Event) {
		if c, ok := engine.CueOf(e); ok {
			cues = append(cues, c)
		}
	})
	w := s.NewRun(3, game.Start{})
	var policy harness.Policy
	for _, p := range harness.Policies {
		if p.Name == "boss" {
			policy = p.Make(cfg, harness.PolicyOpts{})
		}
	}
	for d := 0; d < 120 && w.Over == nil; d++ {
		if c := w.Dilemmas.Pending; c != nil {
			_, _ = s.Choose(0)
		}
		policy(w)
		s.EndDay()
	}
	seen := map[engine.CueKind]int{}
	for _, c := range cues {
		seen[c.Kind]++
		if c.Day <= 0 {
			t.Fatalf("a cue with no day: %+v", c)
		}
		switch c.Kind {
		case engine.CueCornerFlip, engine.CueCornerClaimed, engine.CueStrike:
			if w.Corner(c.Corner) == nil {
				t.Fatalf("%s names no corner: %+v", c.Kind, c)
			}
			if c.Kind == engine.CueCornerFlip && (c.From == "" || c.To == "" || c.From == c.To) {
				t.Fatalf("a flip with no change of hands: %+v", c)
			}
		case engine.CueShipment:
			if c.Route == "" || w.City(c.From) == nil || w.City(c.To) == nil || c.Shipment == 0 {
				t.Fatalf("a shipment with no route or ends: %+v", c)
			}
		case engine.CueCrewJoined, engine.CueCrewLeft, engine.CueCrewDown, engine.CueCrewBack:
			if c.Member == 0 {
				t.Fatalf("a crew cue with no member: %+v", c)
			}
		case engine.CuePolice:
			if w.City(c.City) == nil || c.Level == "" {
				t.Fatalf("the police nowhere: %+v", c)
			}
		}
	}
	for _, k := range []engine.CueKind{engine.CueCornerClaimed, engine.CueShipment, engine.CueCrewJoined, engine.CueSale, engine.CuePolice} {
		if seen[k] == 0 {
			t.Errorf("120 days of the boss and no %s cue (%v)", k, seen)
		}
	}
}

// The cue table's markers in docs/engine.md.
const (
	cuesBegin = "<!-- cues:begin (generated by TestCueTableIsCurrent -update) -->"
	cuesEnd   = "<!-- cues:end -->"
)

// cueTable is docs/engine.md's audit (#301): every cue with the kinds
// that give it, then every kind that gives none.
func cueTable() string {
	byCue := map[engine.CueKind][]string{}
	var none []string
	for _, e := range events.All {
		if k := engine.CueKindOf(e.Kind()); k != "" {
			byCue[k] = append(byCue[k], e.Kind())
		} else {
			none = append(none, e.Kind())
		}
	}
	cues := make([]string, 0, len(byCue))
	for k := range byCue {
		cues = append(cues, string(k))
	}
	sort.Strings(cues)
	var b strings.Builder
	b.WriteString("| Cue | From the events |\n|---|---|\n")
	for _, k := range cues {
		kinds := byCue[engine.CueKind(k)]
		sort.Strings(kinds)
		fmt.Fprintf(&b, "| `%s` | %s |\n", k, "`"+strings.Join(kinds, "`, `")+"`")
	}
	sort.Strings(none)
	fmt.Fprintf(&b, "\nThe report's and the journal's alone, no cue (%d): %s.\n", len(none), "`"+strings.Join(none, "`, `")+"`")
	return b.String()
}

// TestCueTableIsCurrent (#301): the table in docs/engine.md is
// cueTable; -update writes it between the markers.
func TestCueTableIsCurrent(t *testing.T) {
	const path = "../../docs/engine.md"
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	doc := string(raw)
	i, j := strings.Index(doc, cuesBegin), strings.Index(doc, cuesEnd)
	if i < 0 || j < i {
		t.Fatalf("docs/engine.md has no cue table markers")
	}
	want := cuesBegin + "\n" + cueTable() + cuesEnd
	got := doc[i : j+len(cuesEnd)]
	if got == want {
		return
	}
	if *update {
		if err := os.WriteFile(path, []byte(doc[:i]+want+doc[j+len(cuesEnd):]), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatal("the cue table in docs/engine.md is stale: go test ./internal/engine -run TestCueTableIsCurrent -update")
}
