package protocol

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"

	"github.com/theclifmeister/kingpin/internal/content"
	"github.com/theclifmeister/kingpin/internal/game"
	"github.com/theclifmeister/kingpin/internal/harness"
)

// quoteNames parses internal/engine/quotes.go for every rule's
// parameter and result names, keyed Market.Capacity.
func quoteNames(t *testing.T) map[string]ruleSig {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), "../engine/quotes.go", nil, 0)
	if err != nil {
		t.Fatal(err)
	}
	names := func(fl *ast.FieldList) []string {
		var out []string
		if fl == nil {
			return nil
		}
		for _, fd := range fl.List {
			if len(fd.Names) == 0 {
				out = append(out, "")
			}
			for _, n := range fd.Names {
				out = append(out, n.Name)
			}
		}
		return out
	}
	sigs := map[string]ruleSig{}
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		it, ok := ts.Type.(*ast.InterfaceType)
		if !ok || !strings.HasSuffix(ts.Name.Name, "Rules") {
			return false
		}
		sim := strings.TrimSuffix(ts.Name.Name, "Rules")
		for _, m := range it.Methods.List {
			ft, ok := m.Type.(*ast.FuncType)
			if !ok || len(m.Names) != 1 {
				continue
			}
			res := names(ft.Results)
			if len(res) < 2 {
				res = nil
			}
			sigs[ruleKey(sim, m.Names[0].Name)] = ruleSig{params: names(ft.Params), results: res}
		}
		return false
	})
	return sigs
}

// TestRuleNamesAreCurrent (#325): rules_names.go is quotes.go's names;
// `go test ./internal/protocol -run TestRuleNamesAreCurrent -update`
// rewrites it.
func TestRuleNamesAreCurrent(t *testing.T) {
	sigs := quoteNames(t)
	keys := make([]string, 0, len(sigs))
	for k := range sigs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	quote := func(ss []string) string {
		if ss == nil {
			return "nil"
		}
		q := make([]string, len(ss))
		for i, s := range ss {
			q[i] = fmt.Sprintf("%q", s)
		}
		return "[]string{" + strings.Join(q, ", ") + "}"
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by TestRuleNamesAreCurrent -update; DO NOT EDIT.\n\npackage protocol\n\n")
	b.WriteString("// ruleSig is a rule's parameter and result names as internal/engine/quotes.go\n// declares them: reflection cannot see them, and the schema and the errors\n// name them.\ntype ruleSig struct{ params, results []string }\n\nvar ruleNames = map[string]ruleSig{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q: {%s, %s},\n", k, quote(sigs[k].params), quote(sigs[k].results))
	}
	b.WriteString("}\n")
	want, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile("rules_names.go")
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Equal(got, want) {
		return
	}
	if *update {
		if err := os.WriteFile("rules_names.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatal("rules_names.go is stale: go test ./internal/protocol -run TestRuleNamesAreCurrent -update")
}

// TestEveryRuleIsClassed (#325): every method of every engine.Rules
// interface is on the wire as rules.<sim>.<method> or in unservedRules
// with its reason, and every rule has its names from quotes.go.
func TestEveryRuleIsClassed(t *testing.T) {
	t.Parallel()
	all := 0
	for i := 0; i < rulesType.NumField(); i++ {
		f := rulesType.Field(i)
		for j := 0; j < f.Type.NumMethod(); j++ {
			all++
			name := f.Type.Method(j).Name
			key := ruleKey(f.Name, name)
			_, served := methods[ruleMethodName(f.Name, name)]
			_, refused := unservedRules[key]
			if served == refused {
				t.Errorf("%s: served %v, unserved %v: it must be one", key, served, refused)
			}
			if _, ok := ruleNames[key]; !ok {
				t.Errorf("%s has no names: run TestRuleNamesAreCurrent -update", key)
			}
		}
	}
	for key := range unservedRules {
		sim, name, _ := strings.Cut(key, ".")
		f, ok := rulesType.FieldByName(sim)
		if !ok {
			t.Errorf("unservedRules names %s, and Rules has no %s", key, sim)
			continue
		}
		if _, ok := f.Type.MethodByName(name); !ok {
			t.Errorf("unservedRules names %s, and %sRules has no %s", key, sim, name)
		}
	}
	if got := len(rulesServed()); got != all-len(unservedRules) || got < 140 {
		t.Errorf("%d rules served of %d", got, all)
	}
}

// truths are the types a quote never carries: the run itself, a
// faction's or the chief's true state, a planted fact, a route's true
// risk. TestNoTruthOnTheWire walks every rule's result for them.
var truths = []reflect.Type{
	reflect.TypeFor[game.World](), reflect.TypeFor[game.RivalState](), reflect.TypeFor[game.Chief](),
	reflect.TypeFor[game.Fact](), reflect.TypeFor[content.RouteConfig](),
}

// TestNoTruthOnTheWire (#325): no rule's result on the wire holds a
// truth type anywhere inside it.
func TestNoTruthOnTheWire(t *testing.T) {
	t.Parallel()
	var holds func(typ reflect.Type, seen map[reflect.Type]bool) reflect.Type
	holds = func(typ reflect.Type, seen map[reflect.Type]bool) reflect.Type {
		if seen[typ] {
			return nil
		}
		seen[typ] = true
		for _, tr := range truths {
			if typ == tr {
				return tr
			}
		}
		switch typ.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			return holds(typ.Elem(), seen)
		case reflect.Struct:
			for i := 0; i < typ.NumField(); i++ {
				if tr := holds(typ.Field(i).Type, seen); tr != nil {
					return tr
				}
			}
		}
		return nil
	}
	for _, r := range rulesServed() {
		m := methods[ruleMethodName(r[0], r[1])]
		if m.result == nil {
			continue
		}
		if tr := holds(m.result, map[reflect.Type]bool{}); tr != nil {
			t.Errorf("%s answers with a %s inside", m.name, tr)
		}
	}
}

// quoteRig is a run sixty days into the boss's game with one of every
// thing a rule takes by id: a held corner, a deeded one, a house, a
// front, a crew member, a contract.
type quoteRig struct {
	srv *Server
	w   *game.World
}

func newQuoteRig(t *testing.T) quoteRig {
	t.Helper()
	cfg := content.MustLoad()
	srv, err := NewServer(cfg)
	if err != nil {
		t.Fatal(err)
	}
	s := srv.Session()
	w := s.NewRun(7, game.Start{})
	var policy harness.Policy
	for _, p := range harness.Policies {
		if p.Name == "boss" {
			policy = p.Make(cfg, harness.PolicyOpts{})
		}
	}
	for d := 0; d < 60 && w.Over == nil; d++ {
		if w.Dilemmas.Pending != nil {
			_, _ = s.Choose(0)
		}
		policy(w)
		s.EndDay()
	}
	if w.Over != nil || w.Day < 60 {
		t.Fatalf("the boss's run is on day %d, over %v", w.Day, w.Over != nil)
	}
	w.Player.DirtyCash += 5_000_000
	w.Player.CleanCash += 5_000_000
	if len(w.Houses) == 0 {
		offers := s.HouseOffers()
		if len(offers) == 0 {
			t.Fatal("no house on offer")
		}
		if _, err := s.BuyHouse(offers[0].ID); err != nil {
			t.Fatal(err)
		}
	}
	if len(w.Contracts) == 0 {
		w.OfferContract(game.Contract{Buyer: "test", City: w.Player.Location, Product: w.Products[0], Units: 10, Premium: 1.2, Expires: w.Day + 5})
	}
	return quoteRig{srv: srv, w: w}
}

// arg is one of the rig's things for a parameter: what the wire sends
// and the Go value the rule takes.
func (q quoteRig) arg(t *testing.T, name string, typ reflect.Type) (any, reflect.Value) {
	t.Helper()
	w, s := q.w, q.srv.Session()
	held := func() *game.Corner {
		for _, c := range w.Corners() {
			if c.Held() {
				return w.Corner(c.ID)
			}
		}
		t.Fatal("no corner held")
		return nil
	}
	switch typ {
	case reflect.TypeFor[*game.Corner]():
		c := held()
		return c.ID, reflect.ValueOf(c)
	case reflect.TypeFor[game.Corner]():
		c := held()
		return c.ID, reflect.ValueOf(*c)
	case reflect.TypeFor[*game.Deed]():
		c := held()
		if c.Deed == nil {
			c.Deed = &game.Deed{Bought: w.Day, Price: 1000}
		}
		return c.ID, reflect.ValueOf(c.Deed)
	case reflect.TypeFor[*game.RivalState]():
		r := w.Rival()
		return r.Faction(), reflect.ValueOf(r)
	case reflect.TypeFor[*game.Supplier]():
		sup := w.SuppliersIn(w.Player.Location)[0]
		return sup.ID, reflect.ValueOf(sup)
	case reflect.TypeFor[*game.City]():
		c := w.City(w.Player.Location)
		return c.ID, reflect.ValueOf(c)
	case reflect.TypeFor[*game.House]():
		h := w.House(w.Houses[0].ID)
		return h.ID, reflect.ValueOf(h)
	case reflect.TypeFor[game.Front]():
		o := s.Rules().Laundering.Offers()[0]
		return o.ID, reflect.ValueOf(game.Front{ID: o.ID, Name: o.Name})
	case reflect.TypeFor[game.CrewMember]():
		m := w.Crew.Members[0]
		return m.ID, reflect.ValueOf(m)
	case reflect.TypeFor[game.Contract]():
		c := w.Contracts[0]
		return c.ID, reflect.ValueOf(c)
	case reflect.TypeFor[content.RouteConfig]():
		cities := make([]string, 0, len(w.Cities))
		for cid := range w.Cities {
			cities = append(cities, cid)
		}
		sort.Strings(cities)
		for _, cid := range cities {
			if rs := s.Rules().Logistics.RoutesOpen(w, cid); len(rs) > 0 {
				return rs[0].ID, reflect.ValueOf(rs[0])
			}
		}
		t.Fatal("no route open")
	case reflect.TypeFor[content.LaneConfig]():
		l := s.Rules().Logistics.Lanes()[0]
		return l.ID, reflect.ValueOf(l)
	case reflect.TypeFor[game.Deal]():
		return DealParams{Kind: "truce", Terms: TermsParams{Days: 10}}, reflect.ValueOf(game.Deal{Kind: "truce", Terms: game.Terms{Days: 10}})
	}
	if names := dialNames(typ); names != nil {
		return names[1], reflect.ValueOf(1).Convert(typ)
	}
	var v any
	switch name {
	case "day":
		v = w.Day + 1
	case "city":
		v = w.Player.Location
	case "name": // a trait by name (#346)
		v = "steady"
	case "product":
		v = w.Products[0]
	case "id":
		v = s.Rules().Laundering.AssetOffers()[0].ID
	case "muscle", "skill", "n", "band":
		v = 2
	case "rel", "quality", "share", "mul", "base":
		v = 0.5
	default:
		v = 100
	}
	return v, reflect.ValueOf(v).Convert(typ)
}

// quote calls a method on the rig's server and returns its result, or
// fails; a quote sends nothing but its response.
func (q quoteRig) quote(t *testing.T, method string, params ...any) (json.RawMessage, *Error) {
	t.Helper()
	req, err := json.Marshal(map[string]any{"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
	if err != nil {
		t.Fatal(err)
	}
	lines := q.srv.Handle(req)
	var resp Response
	if err := json.Unmarshal(lines[len(lines)-1], &resp); err != nil {
		t.Fatal(err)
	}
	if strings.HasPrefix(method, "rules.") && resp.Error == nil && len(lines) != 1 {
		t.Errorf("%s sent %d lines: a quote sends only its answer", method, len(lines))
	}
	return resp.Result, resp.Error
}

// TestEveryQuoteIsTheRules (#325): every rule served, asked over the
// wire about the rig's things, answers what Session.Rules answers about
// them in this process, and the quotes leave the run as it was.
func TestEveryQuoteIsTheRules(t *testing.T) {
	t.Parallel()
	q := newQuoteRig(t)
	for _, typ := range []reflect.Type{reflect.TypeFor[*game.Deed]()} {
		q.arg(t, "", typ) // the deed the rig lays before the world is weighed
	}
	before, err := json.Marshal(q.w)
	if err != nil {
		t.Fatal(err)
	}
	rules := reflect.ValueOf(q.srv.Session().Rules())
	for _, r := range rulesServed() {
		sim, name := r[0], r[1]
		fn := rules.FieldByName(sim).MethodByName(name)
		ft := fn.Type()
		sig := ruleNames[ruleKey(sim, name)]
		var wire []any
		var args []reflect.Value
		for i := 0; i < ft.NumIn(); i++ {
			if ft.In(i) == worldType {
				args = append(args, reflect.ValueOf(q.w))
				continue
			}
			wv, gv := q.arg(t, sig.params[i], ft.In(i))
			wire = append(wire, wv)
			args = append(args, gv)
		}
		got, rerr := q.quote(t, ruleMethodName(sim, name), wire...)
		if rerr != nil {
			t.Errorf("%s: %v", ruleMethodName(sim, name), rerr)
			continue
		}
		out := fn.Call(args)
		var want any
		switch {
		case len(out) == 2 && out[1].Kind() == reflect.Bool:
			want = wireResult(out[0])
		case len(out) == 2:
			want = map[string]any{snake(sig.results[0]): out[0].Interface(), snake(sig.results[1]): out[1].Interface()}
		case len(out) == 1:
			want = wireResult(out[0])
		}
		wantJSON, err := json.Marshal(want)
		if err != nil {
			t.Fatal(err)
		}
		if !sameJSON(got, wantJSON) {
			t.Errorf("%s: the wire says %s, the rules %s", ruleMethodName(sim, name), trim(got), trim(wantJSON))
		}
	}
	after, err := json.Marshal(q.w)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Error("the quotes changed the run")
	}
}

// sameJSON reports whether two documents say the same, whatever order
// their keys are in.
func sameJSON(a, b []byte) bool {
	var x, y any
	if json.Unmarshal(a, &x) != nil || json.Unmarshal(b, &y) != nil {
		return false
	}
	return reflect.DeepEqual(x, y)
}

func trim(b []byte) string {
	if len(b) > 200 {
		return string(b[:200]) + "…"
	}
	return string(b)
}

// TestQuoteRefusals (#325): a thing the run does not have, a day past
// tomorrow and a rule with no run are refused as bad params; an asset
// asked about that is not on offer is the game saying no.
func TestQuoteRefusals(t *testing.T) {
	t.Parallel()
	q := newQuoteRig(t)
	for _, c := range []struct {
		method string
		params []any
		code   int
	}{
		{"rules.territory.deed_price", []any{"nowhere"}, CodeInvalidParams},
		{"rules.rivals.scout_odds", []any{"nobody"}, CodeInvalidParams},
		{"rules.crew.bail_cost", []any{99999}, CodeInvalidParams},
		{"rules.logistics.watched", []any{q.w.Day + 2}, CodeInvalidParams},
		{"rules.logistics.watched", []any{q.w.Day - 1}, CodeInvalidParams},
		{"rules.market.dial", []any{"reckless"}, CodeInvalidParams},
		{"rules.laundering.asset_offer", []any{"nothing"}, CodeRefused},
		{"rules.crew.investigate_cost", []any{1}, CodeInvalidParams},
		{"rules.logistics.route", []any{"any"}, CodeNoMethod},
	} {
		_, err := q.quote(t, c.method, c.params...)
		if err == nil || err.Code != c.code {
			t.Errorf("%s %v: %v, want code %d", c.method, c.params, err, c.code)
		}
	}
	if _, err := q.quote(t, "rules.logistics.watched", q.w.Day); err != nil {
		t.Errorf("today refused: %v", err)
	}
	srv, err := NewServer(content.MustLoad())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := (quoteRig{srv: srv}).quote(t, "rules.crew.investigate_cost"); err == nil || err.Code != CodeNoRun {
		t.Errorf("a quote with no run: %v", err)
	}
}

// TestQuotedIsCharged (#325): a front end that quotes a move over the
// wire and makes it pays the quote: the investigation, the block.
func TestQuotedIsCharged(t *testing.T) {
	t.Parallel()
	q := newQuoteRig(t)
	w := q.w
	var cost int
	raw, rerr := q.quote(t, "rules.crew.investigate_cost")
	if rerr != nil || json.Unmarshal(raw, &cost) != nil || cost <= 0 {
		t.Fatalf("investigate_cost: %s %v", raw, rerr)
	}
	if _, rerr := q.quote(t, "investigate"); rerr != nil {
		t.Fatal(rerr)
	}
	if w.Today.Investigation.Cost != cost {
		t.Errorf("the investigation cost %d, quoted %d", w.Today.Investigation.Cost, cost)
	}

	var corner string
	for _, c := range w.Corners() {
		if c.Held() && !c.Deeded() {
			corner = c.ID
			break
		}
	}
	if corner == "" {
		t.Fatal("no held corner without a deed")
	}
	var price int
	raw, rerr = q.quote(t, "rules.territory.deed_price", corner)
	if rerr != nil || json.Unmarshal(raw, &price) != nil || price <= 0 {
		t.Fatalf("deed_price: %s %v", raw, rerr)
	}
	w.Stats.Laundered += 10 * price
	// The block's price is the corner's trade, which the rig's run sets
	// (the deck it answers moved it past the $5M top-up in #342): the
	// test is the quote, not the pile, so the pile covers it.
	w.Player.CleanCash = max(w.Player.CleanCash, price)
	clean := w.Player.CleanCash
	if _, rerr := q.quote(t, "buy_deed", corner); rerr != nil {
		t.Fatal(rerr)
	}
	if paid := clean - w.Player.CleanCash; paid != price {
		t.Errorf("the block cost %d, quoted %d", paid, price)
	}
}
